// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crescent/oracle/v1beta1/event.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventSymbolRate is emitted on exchange rate update
type EventSymbolRate struct {
	SymbolDenom string `protobuf:"bytes,1,opt,name=symbol_denom,json=symbolDenom,proto3" json:"symbol_denom,omitempty"`
	// Exchange rate (based to USD)
	Rate    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=rate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rate"`
	Feeders []string                               `protobuf:"bytes,3,rep,name=feeders,proto3" json:"feeders,omitempty"`
}

func (m *EventSymbolRate) Reset()         { *m = EventSymbolRate{} }
func (m *EventSymbolRate) String() string { return proto.CompactTextString(m) }
func (*EventSymbolRate) ProtoMessage()    {}
func (*EventSymbolRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_db8e35c96879f617, []int{0}
}
func (m *EventSymbolRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSymbolRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSymbolRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSymbolRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSymbolRate.Merge(m, src)
}
func (m *EventSymbolRate) XXX_Size() int {
	return m.Size()
}
func (m *EventSymbolRate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSymbolRate.DiscardUnknown(m)
}

var xxx_messageInfo_EventSymbolRate proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EventSymbolRate)(nil), "crescent.oracle.v1beta1.EventSymbolRate")
}

func init() {
	proto.RegisterFile("crescent/oracle/v1beta1/event.proto", fileDescriptor_db8e35c96879f617)
}

var fileDescriptor_db8e35c96879f617 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x1b, 0x27, 0xca, 0xaa, 0x20, 0x14, 0xc1, 0xba, 0x8b, 0x6c, 0x2a, 0xc8, 0x6e, 0x96,
	0x30, 0x44, 0x1f, 0xa0, 0xcc, 0x17, 0xa8, 0x5e, 0x79, 0x33, 0xda, 0xf4, 0x58, 0x65, 0x6b, 0xcf,
	0x48, 0x62, 0x75, 0x6f, 0x21, 0x3e, 0x55, 0x2f, 0x77, 0x29, 0x5e, 0x0c, 0x6d, 0x5f, 0x44, 0x9a,
	0xb4, 0xe2, 0x55, 0xf2, 0x7f, 0xf9, 0x4f, 0x7e, 0xce, 0xef, 0x5e, 0x08, 0x09, 0x4a, 0x40, 0xae,
	0x39, 0xca, 0x48, 0x2c, 0x81, 0x17, 0xd3, 0x18, 0x74, 0x34, 0xe5, 0x50, 0x40, 0xae, 0xd9, 0x4a,
	0xa2, 0x46, 0xef, 0xa4, 0x33, 0x31, 0x6b, 0x62, 0xad, 0x69, 0x70, 0x2a, 0x50, 0x65, 0xa8, 0xe6,
	0xc6, 0xc6, 0xad, 0xb0, 0x33, 0x83, 0xe3, 0x14, 0x53, 0xb4, 0xbc, 0xb9, 0x59, 0x7a, 0xfe, 0x41,
	0xdc, 0xa3, 0xdb, 0xe6, 0xe7, 0xbb, 0x75, 0x16, 0xe3, 0x32, 0x8c, 0x34, 0x78, 0x67, 0xee, 0xa1,
	0x32, 0x6a, 0x9e, 0x40, 0x8e, 0x99, 0x4f, 0x46, 0x64, 0xdc, 0x0f, 0x0f, 0x2c, 0x9b, 0x35, 0xc8,
	0x0b, 0xdc, 0x5d, 0x19, 0x69, 0xf0, 0x77, 0x9a, 0xa7, 0x80, 0x95, 0xdb, 0xa1, 0xf3, 0xb5, 0x1d,
	0x5e, 0xa6, 0xcf, 0xfa, 0xe9, 0x25, 0x66, 0x02, 0xb3, 0x36, 0xbb, 0x3d, 0x26, 0x2a, 0x59, 0x70,
	0xbd, 0x5e, 0x81, 0x62, 0x33, 0x10, 0xa1, 0x99, 0xf5, 0x7c, 0x77, 0xff, 0x11, 0x20, 0x01, 0xa9,
	0xfc, 0xde, 0xa8, 0x37, 0xee, 0x87, 0x9d, 0x0c, 0xee, 0xcb, 0x1f, 0xea, 0x94, 0x15, 0x25, 0x9b,
	0x8a, 0x92, 0xef, 0x8a, 0x92, 0xf7, 0x9a, 0x3a, 0x9b, 0x9a, 0x3a, 0x9f, 0x35, 0x75, 0x1e, 0x6e,
	0xfe, 0xa7, 0xb4, 0x3d, 0x4c, 0x72, 0xd0, 0xaf, 0x28, 0x17, 0x7f, 0x80, 0x17, 0xd7, 0xfc, 0xad,
	0xab, 0xd0, 0x24, 0xc7, 0x7b, 0x66, 0xe3, 0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0xe4,
	0xf5, 0xba, 0x62, 0x01, 0x00, 0x00,
}

func (m *EventSymbolRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSymbolRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSymbolRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Feeders) > 0 {
		for iNdEx := len(m.Feeders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Feeders[iNdEx])
			copy(dAtA[i:], m.Feeders[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.Feeders[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.Rate.Size()
		i -= size
		if _, err := m.Rate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.SymbolDenom) > 0 {
		i -= len(m.SymbolDenom)
		copy(dAtA[i:], m.SymbolDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SymbolDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventSymbolRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SymbolDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Rate.Size()
	n += 1 + l + sovEvent(uint64(l))
	if len(m.Feeders) > 0 {
		for _, s := range m.Feeders {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventSymbolRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSymbolRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSymbolRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SymbolDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SymbolDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feeders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feeders = append(m.Feeders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
